#include <atomic>
#include <cstdint>
#include <initializer_list>
#include <limits>
#include <memory>
#include <string>
#include <utility>

#include "engine/records/identity.hpp"
#include "engine/records/payload.hpp"
#include "engine/storage/database.hpp"
#include "engine/storage/memory_store.hpp"
#include "modules/files/data/repository.hpp"
#include "modules/files/module.hpp"
#include "modules/registry.hpp"
#include "support/check.hpp"

using squiflow::testing::check;using squiflow::testing::section;
namespace engine=squiflow::engine;namespace modules=squiflow::modules;namespace files=squiflow::modules::files;namespace protocol=squiflow::protocol;
namespace {
std::atomic<std::int64_t> g_now{1'800'000'000'000};std::int64_t now(){return g_now.fetch_add(1000)+1000;}std::atomic<int> g_key{0};std::string key(){return "file-key-"+std::to_string(++g_key);}
const std::string kPerson="a1000000000000000000000000000001",kDevice="a2000000000000000000000000000001",kVolume="a3000000000000000000000000000001",kAssetA="a4000000000000000000000000000001",kAssetB="a4000000000000000000000000000002",kLocA="a5000000000000000000000000000001",kLocB="a5000000000000000000000000000002",kLink="a6000000000000000000000000000001",kTarget="a7000000000000000000000000000001";
const std::string hA="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",hB="bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";
engine::Blob payload(std::initializer_list<std::pair<std::string,std::string>> ts={},std::initializer_list<std::pair<std::string,std::int64_t>> ns={}){engine::Row r;for(auto&[n,v]:ts)r.set(n,engine::Value::text(v));for(auto&[n,v]:ns)r.set(n,engine::Value::integer(v));return engine::encode_payload(r);}
engine::Session owner(){engine::Session s;s.person=engine::record_id_from_string(kPerson);s.device={1,1};s.is_owner=true;s.rights.grant_all();return s;}engine::Session staff(std::initializer_list<protocol::RightId> rs){engine::Session s;s.person=engine::record_id_from_string(kPerson);s.device={1,2};for(auto r:rs)s.rights.grant(r);return s;}
template<class F>bool violates(F&&f){try{f();}catch(const modules::RuleViolation&){return true;}return false;}
struct Shop{modules::Registry registry{now};std::unique_ptr<engine::Database> database;Shop(){registry.add(files::make_module(now));engine::MigrationRunner runner{now};registry.collect_migrations(runner);database=std::make_unique<engine::Database>(std::make_unique<engine::MemoryStore>(),std::move(runner));database->open();}modules::Outcome run(protocol::OperationId op,const std::string&id,const engine::Blob&body,const engine::Session&s,engine::ConnectionState c=engine::ConnectionState::Online,bool with_key=true){modules::Call call;call.operation=op;call.record_id=id;call.payload=body;if(protocol::operation(op).sync_class==protocol::OperationClass::Synchronizable)call.idempotency_key=with_key?key():std::string{};return registry.run(*database,call,s,c);}template<class F>void read(F&&f)const{database->read([&](const engine::Store&s){f(s);});}};
engine::Blob scan(const std::string&asset=kAssetA,const std::string&loc=kLocA,const std::string&file="ntfs-1",const std::string&path="D:/Design/card.cdr",const std::string&hash=hA,std::int64_t generation=1,bool complete=true,std::int64_t count=1){return payload({{"device_id",kDevice},{"volume_id","VOL-D"},{"volume_record_id",kVolume},{"volume_label","Designs"},{"item.0.location_id",loc},{"item.0.asset_id",asset},{"item.0.file_id",file},{"item.0.path",path},{"item.0.content_hash",hash},{"item.0.extension","CDR"},{"item.0.media_type","application/coreldraw"}},{{"generation",generation},{"complete",complete?1:0},{"online",1},{"item_count",count},{"item.0.size_bytes",4096},{"item.0.modified_at",1'700'000'000'000}});}
std::int64_t mod(protocol::ModuleId m){return static_cast<std::int64_t>(m);}
}
int main(){const auto session=owner();
section("migration 21 and exact files operation surface");{Shop shop;check(shop.registry.handled(protocol::OperationId::file_index_scan),"scan handled");check(shop.registry.handled(protocol::OperationId::file_search),"search handled");check(shop.registry.handled(protocol::OperationId::file_link),"link handled");check(shop.registry.handled(protocol::OperationId::file_forget),"forget handled");check(!shop.registry.handled(protocol::OperationId::task_create),"nothing else claimed");check(files::tables::kFirstMigration==21,"migration 21");auto&scanop=protocol::operation(protocol::OperationId::file_index_scan);auto&search=protocol::operation(protocol::OperationId::file_search);auto&link=protocol::operation(protocol::OperationId::file_link);auto&forget=protocol::operation(protocol::OperationId::file_forget);check(scanop.sync_class==protocol::OperationClass::LocalOnly,"scan local");check(search.sync_class==protocol::OperationClass::LocalOnly,"search local");check(link.sync_class==protocol::OperationClass::Synchronizable,"link sync");check(forget.sync_class==protocol::OperationClass::Synchronizable,"forget sync");check(scanop.right==protocol::RightId::right_file_index&&link.right==protocol::RightId::right_file_index&&forget.right==protocol::RightId::right_file_index,"index right exact");check(search.right==protocol::RightId::right_file_search,"search right exact");check(scanop.offline==protocol::OfflineRule::OfflineAllowed&&search.offline==protocol::OfflineRule::OfflineAllowed&&link.offline==protocol::OfflineRule::OfflineAllowed&&forget.offline==protocol::OfflineRule::OfflineAllowed,"all offline allowed");shop.read([](const engine::Store&s){check(s.has_table(files::tables::kAsset),"asset table");check(s.has_table(files::tables::kLocation),"location table");check(s.has_table(files::tables::kLink),"link table");check(s.has_table(files::tables::kVolume),"volume table");});}
section("SHA-256 and local identity boundaries are exact");{check(files::normalize_sha256(hA)==hA,"lowercase hash");check(files::normalize_sha256("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")==hA,"uppercase normalized");check(!files::normalize_sha256(std::string(63,'a')),"63 refused");check(!files::normalize_sha256(std::string(65,'a')),"65 refused");check(!files::normalize_sha256(std::string(64,'z')),"nonhex refused");check(!files::normalize_sha256(std::string(64,'0')),"zero digest refused");files::FileAsset a;a.id=kAssetA;a.content_hash=hA;a.created_at=1;a.created_by=kPerson;check(!violates([&]{files::validate(a);}),"minimal asset valid");a.size_bytes=-1;check(violates([&]{files::validate(a);}),"negative size refused");a.size_bytes=0;a.predecessor_id=kAssetA;check(violates([&]{files::validate(a);}),"self predecessor refused");engine::LocalFileIdentity x{engine::record_id_from_string(kDevice),"VOL","1"},y=x;check(x.is_valid()&&x==y,"stable identity exact");y.volume_id="OTHER";check(!(x==y),"volume distinguishes identity");}
section("scan preserves rename, collapses copies, and creates real versions");{Shop shop;auto first=shop.run(protocol::OperationId::file_index_scan,"",scan(),session,engine::ConnectionState::Offline);check(first.ok&&!first.queued,"local scan offline never queues");shop.read([](const engine::Store&s){check(s.count(files::tables::kAsset)==1,"one asset");check(s.count(files::tables::kLocation)==1,"one location");auto l=files::data::find_location(s,kLocA);check(l->path=="D:/Design/card.cdr","path saved");check(l->identity.file_id=="ntfs-1","file id saved");check(l->presence==files::Presence::Present,"present");check(files::data::find_volume(s,kVolume)->scan_generation==1,"generation saved");});
 check(shop.run(protocol::OperationId::file_index_scan,"",scan(kAssetB,kLocA,"ntfs-1","D:/Moved/card.cdr",hA,2),session).ok,"rename scan");shop.read([](const engine::Store&s){check(s.count(files::tables::kAsset)==1,"rename no asset");check(s.count(files::tables::kLocation)==1,"rename no location");check(files::data::find_location(s,kLocA)->path=="D:/Moved/card.cdr","path updated");});
 check(shop.run(protocol::OperationId::file_index_scan,"",scan(kAssetB,kLocB,"ntfs-2","D:/Copy/card.cdr",hA,3,false),session).ok,"copy scan");shop.read([](const engine::Store&s){check(s.count(files::tables::kAsset)==1,"copy same asset");check(s.count(files::tables::kLocation)==2,"copy second location");check(files::data::locations_for_asset(s,kAssetA).size()==2,"duplicates discoverable");});
 check(shop.run(protocol::OperationId::file_index_scan,"",scan(kAssetB,kLocA,"ntfs-1","D:/Moved/card.cdr",hB,4,false),session).ok,"replacement scan");shop.read([](const engine::Store&s){check(s.count(files::tables::kAsset)==2,"new bytes new asset");auto b=files::data::find_asset(s,kAssetB);check(b->predecessor_id==kAssetA,"lineage predecessor");check(files::data::find_location(s,kLocA)->asset_id==kAssetB,"location advances");check(files::data::find_location(s,kLocB)->asset_id==kAssetA,"copy stays old");check(files::data::lineage(s,kAssetB).size()==2,"lineage readable");});
 check(!shop.run(protocol::OperationId::file_index_scan,"",scan(kAssetB,kLocA,"ntfs-1","x",hB,3),session).ok,"stale generation refused");check(!shop.run(protocol::OperationId::file_index_scan,"",scan(kAssetB,kLocA,"ntfs-1","x",std::string(64,'0'),5),session).ok,"bad hash refused");check(!shop.run(protocol::OperationId::file_index_scan,"",scan(kAssetB,kLocA,"ntfs-1","x",hB,5,true,501),session).ok,"oversized scan refused");shop.read([](const engine::Store&s){check(s.count(files::tables::kAsset)==2,"bad scans no asset");check(s.count(files::tables::kLocation)==2,"bad scans no location");});
 check(shop.run(protocol::OperationId::file_index_scan,"",scan(kAssetB,kLocA,"ntfs-1","D:/Moved/card.cdr",hB,5,true),session).ok,"complete scan");shop.read([](const engine::Store&s){check(files::data::find_location(s,kLocA)->presence==files::Presence::Present,"seen remains present");check(files::data::find_location(s,kLocB)->presence==files::Presence::Missing,"unseen becomes missing");});}
section("links pin versions, search stays local, and forgetting never erases evidence");{Shop shop;shop.run(protocol::OperationId::file_index_scan,"",scan(),session);auto linked=shop.run(protocol::OperationId::file_link,kLink,payload({{"asset_id",kAssetA},{"target_record",kTarget},{"role","printed"},{"search_text","300gsm school card"}},{{"target_module",mod(protocol::ModuleId::jobs)}}),session);check(linked.ok&&linked.queued,"link sync queued");check(!shop.run(protocol::OperationId::file_link,"a6000000000000000000000000000002",payload({{"asset_id",kAssetA},{"target_record",kTarget},{"role","printed"}},{{"target_module",mod(protocol::ModuleId::jobs)}}),session).ok,"duplicate equivalent link refused");auto found=shop.run(protocol::OperationId::file_search,"",payload({{"query","300GSM"}},{{"limit",10}}),session,engine::ConnectionState::Offline);check(found.ok&&!found.queued&&found.rows.size()==1,"tag search local casefolded");check(found.rows[0].get("linked").boolean_or(false),"linked projection");auto dup=shop.run(protocol::OperationId::file_search,"",payload({},{{"duplicates_only",1}}),session);check(dup.ok&&dup.rows.empty(),"not duplicate yet");check(!shop.run(protocol::OperationId::file_search,"",payload({},{{"limit",0}}),session).ok,"zero limit refused");check(!shop.run(protocol::OperationId::file_search,"",payload({},{{"limit",501}}),session).ok,"501 refused");check(shop.run(protocol::OperationId::file_search,"",payload({},{{"limit",500}}),session).ok,"500 accepted");auto forgot=shop.run(protocol::OperationId::file_forget,kAssetA,payload({{"reason","Customer requested removal"}}),session);check(forgot.ok&&forgot.queued,"forget sync queued");check(!shop.run(protocol::OperationId::file_forget,kAssetA,payload({{"reason","again"}}),session).ok,"double forget refused");auto hidden=shop.run(protocol::OperationId::file_search,"",payload({}),session);check(hidden.ok&&hidden.rows.empty(),"forgotten excluded from search");shop.read([](const engine::Store&s){auto a=files::data::find_asset(s,kAssetA);check(a->forgotten&&a->forget_reason=="Customer requested removal","tombstone evidence");check(files::data::find_location(s,kLocA).has_value(),"location retained");check(files::data::find_link(s,kLink).has_value(),"link retained");check(files::data::links_for_target(s,files::data::find_link(s,kLink)->target).size()==1,"historical target lookup retained");});}
section("rights malformed payloads and idempotency fail safely");{Shop shop;engine::Session nobody;nobody.rights.grant_all();auto no=shop.run(protocol::OperationId::file_search,"",payload({}),nobody);check(!no.ok&&no.reason==engine::DenialReason::NotSignedIn,"authentication first");auto searcher=staff({protocol::RightId::right_file_search});auto indexer=staff({protocol::RightId::right_file_index});check(shop.run(protocol::OperationId::file_search,"",payload({}),searcher,engine::ConnectionState::Offline).ok,"staff offline search exception");check(!shop.run(protocol::OperationId::file_index_scan,"",scan(),searcher).ok,"search cannot index");check(!shop.run(protocol::OperationId::file_search,"",payload({}),indexer).ok,"index cannot search");auto malformed=shop.run(protocol::OperationId::file_index_scan,"",engine::Blob{1,2,3},session);check(!malformed.ok&&malformed.error=="This request could not be read. Please try it again.","malformed standard refusal");shop.run(protocol::OperationId::file_index_scan,"",scan(),session);modules::Call call;call.operation=protocol::OperationId::file_link;call.record_id=kLink;call.payload=payload({{"asset_id",kAssetA},{"target_record",kTarget},{"role","source"}},{{"target_module",mod(protocol::ModuleId::quotations)}});call.idempotency_key="same-file-link";auto first=shop.registry.run(*shop.database,call,session,engine::ConnectionState::Online);auto replay=shop.registry.run(*shop.database,call,session,engine::ConnectionState::Online);check(first.ok&&!first.replayed,"first link");check(replay.ok&&replay.replayed&&!replay.queued,"replay harmless");shop.read([](const engine::Store&s){check(s.count(files::tables::kLink)==1,"one link after replay");});bool loud=false;try{shop.run(protocol::OperationId::file_link,"",call.payload,session);}catch(const modules::RegistryError&){loud=true;}check(loud,"sync link missing record loud");}
return squiflow::testing::report();}
