#include "platform/background_supervisor.hpp"
#include "support/check.hpp"
#include <atomic>
#include <condition_variable>
#include <limits>
#include <mutex>
#include <stdexcept>
#include <string>
#include <thread>
#include <vector>
using squiflow::testing::check;using squiflow::testing::section;namespace p=squiflow::platform;
int main(){
section("service validation");p::BackgroundSupervisor s;bool bad=false;try{s.register_service({});}catch(const std::invalid_argument&){bad=true;}check(bad,"empty service refused");std::atomic<int> sync_runs=0;std::atomic<int> shared_runs=0;s.register_service({"sync",p::BackgroundLane::Synchronization,[&](std::stop_token){++sync_runs;},3,true,false,{}});s.register_service({"shared",p::BackgroundLane::Shared,[&](std::stop_token){++shared_runs;},3,false,false,{}});bad=false;try{s.register_service({"sync",p::BackgroundLane::Shared,[](std::stop_token){},3,false,false,std::nullopt});}catch(const std::invalid_argument&){bad=true;}check(bad,"duplicate refused");s.seal();bad=false;try{s.register_service({"late",p::BackgroundLane::Shared,[](std::stop_token){},3,false,false,std::nullopt});}catch(const std::logic_error&){bad=true;}check(bad,"sealed registry refuses mutation");
section("gating and execution");check(s.trigger("missing",p::BackgroundTrigger::Explicit)==p::SubmissionResult::UnknownService,"unknown service named");check(s.trigger("sync",p::BackgroundTrigger::Explicit)==p::SubmissionResult::Gated,"network job gated");s.set_network_authorized(true);for(int i=0;i<1000&&sync_runs.load()==0;++i)std::this_thread::yield();check(sync_runs==1,"network authorization dispatches pending work");check(s.trigger("shared",p::BackgroundTrigger::Explicit)==p::SubmissionResult::Accepted,"shared accepted");for(int i=0;i<1000&&shared_runs.load()==0;++i)std::this_thread::yield();check(shared_runs==1,"shared worker executes");
section("coalescing and reentrancy");std::mutex m;std::condition_variable cv;bool release=false;std::atomic<int> blocked_runs=0;p::BackgroundSupervisor c;c.register_service({"blocked",p::BackgroundLane::Shared,[&](std::stop_token token){++blocked_runs;auto st=c.status("blocked");check(st.has_value(),"status read reentrant");if(blocked_runs==1){std::unique_lock lock(m);std::stop_callback wake(token,[&]{cv.notify_all();});cv.wait(lock,[&]{return release||token.stop_requested();});}},3,false,false,std::nullopt});c.seal();check(c.trigger("blocked",p::BackgroundTrigger::Explicit)==p::SubmissionResult::Accepted,"blocking task accepted");for(int i=0;i<1000&&blocked_runs.load()==0;++i)std::this_thread::yield();check(c.trigger("blocked",p::BackgroundTrigger::DataChanged)==p::SubmissionResult::Coalesced,"running task coalesces");check(c.trigger("blocked",p::BackgroundTrigger::Idle)==p::SubmissionResult::Coalesced,"burst remains one rerun");{std::lock_guard lock(m);release=true;}cv.notify_all();for(int i=0;i<10000&&blocked_runs.load()<2;++i)std::this_thread::yield();check(blocked_runs==2,"burst creates exactly one rerun");check(c.shutdown(std::chrono::seconds(1))==p::ShutdownResult::Clean,"clean cooperative shutdown");check(c.trigger("blocked",p::BackgroundTrigger::Explicit)==p::SubmissionResult::Stopping,"submission refused after shutdown");
section("failure budget and bounded diagnostics");p::BackgroundSupervisor f;std::atomic<int> failures=0;f.register_service({"fail",p::BackgroundLane::Synchronization,[&](std::stop_token){++failures;throw std::runtime_error(std::string(400,'x'));},2,false,false,std::nullopt});f.seal();check(f.trigger("fail",p::BackgroundTrigger::Explicit)==p::SubmissionResult::Accepted,"first failure accepted");for(int i=0;i<10000;++i){auto st=f.status("fail");if(st&&st->last_outcome==p::BackgroundOutcome::Failed)break;std::this_thread::yield();}check(f.trigger("fail",p::BackgroundTrigger::Explicit)==p::SubmissionResult::Accepted,"second failure accepted");for(int i=0;i<10000;++i){auto st=f.status("fail");if(st&&st->state==p::BackgroundState::Disabled)break;std::this_thread::yield();}auto fs=f.status("fail");check(fs&&fs->state==p::BackgroundState::Disabled,"failure budget disables service");check(fs&&fs->last_error.size()==p::kMaxBackgroundError,"diagnostic error bounded");check(f.trigger("fail",p::BackgroundTrigger::Explicit)==p::SubmissionResult::Disabled,"disabled service refuses work");check(f.shutdown(std::chrono::seconds(1))==p::ShutdownResult::Clean,"failed supervisor shuts down");
section("coarse monotonic schedule and calendar separation");p::BackgroundSupervisor t;std::atomic<int> ticks=0;t.register_service({"tick",p::BackgroundLane::Synchronization,[&](std::stop_token){++ticks;},3,false,false,std::chrono::minutes(1)});t.seal();auto base=p::BackgroundClock::time_point{};t.coarse_tick(base);t.coarse_tick(base+std::chrono::seconds(59));check(ticks==0,"early coarse tick does not run");t.coarse_tick(base+std::chrono::minutes(1));for(int i=0;i<1000&&ticks.load()==0;++i)std::this_thread::yield();check(ticks==1,"interval boundary runs once");t.coarse_tick(base+std::chrono::hours(24));for(int i=0;i<1000&&ticks.load()<2;++i)std::this_thread::yield();check(ticks==2,"missed intervals coalesce to one");t.calendar_day(std::chrono::year{2026}/8/3);t.calendar_day(std::chrono::year{2026}/8/4);check(t.shutdown(std::chrono::seconds(1))==p::ShutdownResult::Clean,"scheduled supervisor shuts down");
section("concurrent status snapshots");p::BackgroundSupervisor q;q.register_service({"q",p::BackgroundLane::Synchronization,[](std::stop_token){},3,false,false,std::nullopt});q.seal();std::atomic<int> reads=0;std::vector<std::thread> readers;for(int n=0;n<4;++n)readers.emplace_back([&]{for(int i=0;i<1000;++i){auto v=q.statuses();if(v.size()==1)++reads;}});for(auto& r:readers)r.join();check(reads==4000,"atomic snapshots support lock-free-facing reads");check(q.shutdown(std::chrono::seconds(1))==p::ShutdownResult::Clean,"snapshot supervisor shuts down");
return squiflow::testing::report();}
