#include "platform/network_monitor.hpp"
#include "platform/network_state.hpp"
#include "platform/testing/fake_network_monitor.hpp"
#include "support/check.hpp"

#include <atomic>
#include <stdexcept>
#include <thread>
#include <vector>

namespace p=squiflow::platform;using squiflow::testing::check;using squiflow::testing::section;
int main(){
section("conservative network policy");p::NetworkSnapshot s;check(!p::has_usable_network(s),"unknown unsupported is not online");s.reachability_supported=true;s.reachability=p::NetworkReachability::Online;check(p::has_usable_network(s),"supported online is usable");s.captive_portal_supported=true;s.captive_portal=true;check(!p::has_usable_network(s),"captive portal is not usable");s.captive_portal=false;s.metered_supported=true;s.metered=true;check(p::should_attempt_server_work(s),"metered still permits required work");check(p::should_defer_optional_transfer(s),"metered defers optional transfers");for(auto r:{p::NetworkReachability::Unknown,p::NetworkReachability::Offline,p::NetworkReachability::LocalOnly,p::NetworkReachability::SiteOnly}){s.reachability=r;check(!p::should_attempt_server_work(s),"ambiguous state is conservative");}
section("observable deterministic state");p::testing::FakeNetworkMonitor fake;std::vector<p::NetworkSnapshot> seen;auto sub=fake.monitor().subscribe([&](const p::NetworkSnapshot& v){seen.push_back(v);});check(sub.active(),"subscription active");check(seen.size()==1&&seen[0].generation==0,"subscriber immediately receives unknown");check(fake.publish_online(),"first online change published");check(seen.size()==2&&seen.back().generation==1,"generation advances once");check(!fake.publish_online(),"identical state coalesced");check(seen.size()==2,"coalesced state not notified");check(fake.publish_offline(),"offline transition published");check(seen.back().reachability==p::NetworkReachability::Offline,"offline retained");auto moved=std::move(sub);check(!sub.active()&&moved.active(),"subscription move transfers ownership");moved.reset();check(fake.monitor().observer_count()==0,"reset unsubscribes");moved.reset();check(fake.monitor().observer_count()==0,"repeated reset safe");
section("failure and reentrancy isolation");int calls=0;auto throwing=fake.monitor().subscribe([&](const p::NetworkSnapshot&){++calls;throw std::runtime_error("observer");});check(calls==1,"throwing observer received initial state");auto healthy=fake.monitor().subscribe([&](const p::NetworkSnapshot&){++calls;});check(fake.publish_online(),"publication survives callback exception");check(calls==4,"other callback still runs");bool empty_refused=false;try{fake.monitor().subscribe({});}catch(const std::invalid_argument&){empty_refused=true;}check(empty_refused,"empty callback refused");healthy.reset();throwing.reset();
section("observer bound and concurrency");std::vector<p::NetworkSubscription> subscriptions;for(std::size_t i=0;i<p::kMaxNetworkObservers;++i)subscriptions.push_back(fake.monitor().subscribe([](const p::NetworkSnapshot&){}));bool bound=false;try{fake.monitor().subscribe([](const p::NetworkSnapshot&){});}catch(const std::length_error&){bound=true;}check(bound,"observer count bounded");subscriptions.clear();std::atomic<bool> done=false;std::atomic<int> reads=0;std::thread reader([&]{while(!done.load()){auto v=fake.monitor().current();(void)v;++reads;}});while(reads.load()==0){std::this_thread::yield();}for(int i=0;i<200;++i){if((i%2)==0)fake.publish_online();else fake.publish_offline();}done=true;reader.join();check(reads>0,"concurrent snapshots are readable");check(fake.monitor().current().generation>=200,"burst generations remain monotonic");
section("fake scenarios");check(fake.publish_metered_online(),"metered scenario available");auto m=fake.monitor().current();check(m.metered&&p::should_defer_optional_transfer(m),"metered semantics retained");check(fake.publish_captive_portal(),"portal scenario available");check(!p::has_usable_network(fake.monitor().current()),"portal refuses online capability");return squiflow::testing::report();}
