#include <array>
#include <string>
#include <vector>
#include "platform/secret_envelope.hpp"
#include "platform/secret_identity.hpp"
#include "platform/secrets.hpp"
#include "platform/testing/fake_secret_store.hpp"
#include "support/check.hpp"
namespace p=squiflow::platform;using squiflow::testing::check;using squiflow::testing::section;
int main(){section("secret identity and secure value");check(p::is_valid_secret_key("sync.refresh-token"),"valid key");check(!p::is_valid_secret_key(""),"empty key refused");check(!p::is_valid_secret_key("../token"),"traversal refused");check(!p::is_valid_secret_key("UPPER"),"uppercase refused");check(!p::is_valid_secret_key(".token"),"leading dot refused");check(!p::is_valid_secret_key("token."),"trailing dot refused");check(!p::is_valid_secret_key("a..b"),"repeated dot refused");check(!p::is_valid_secret_key(std::string(65,'a')),"long key refused");check(p::secret_file_name("sync.token")=="sync.token.dpapi","bounded file name");std::array<std::byte,3> raw{std::byte{1},std::byte{0},std::byte{2}};p::SecretBuffer buffer(raw);check(buffer.size()==3,"binary buffer retained");p::SecretBuffer moved(std::move(buffer));check(buffer.empty()&&moved.size()==3,"move transfers ownership");moved.clear();check(moved.empty(),"clear is idempotent");moved.clear();check(moved.empty(),"second clear safe");
section("versioned envelope");auto envelope=p::encode_secret_envelope(raw);auto decoded=p::decode_secret_envelope(envelope);check(decoded.ok&&decoded.protected_value.size()==3,"envelope round trip");auto bad=envelope;bad[0]=std::byte{0};check(!p::decode_secret_envelope(bad).ok,"bad magic refused");bad=envelope;bad[4]=std::byte{2};check(p::decode_secret_envelope(bad).fault==p::SecretFault::UnsupportedVersion,"unknown version refused");check(!p::decode_secret_envelope(std::span<const std::byte>(envelope).first(5)).ok,"truncation refused");bad=envelope;bad.push_back(std::byte{0});check(!p::decode_secret_envelope(bad).ok,"trailing data refused");bad=envelope;bad[8]=std::byte{0};check(!p::decode_secret_envelope(bad).ok,"zero length refused");
section("deterministic store and rollback");p::testing::FakeSecretStore store;check(store.store("sync.token",raw).ok,"store succeeds");auto loaded=store.load("sync.token");check(loaded.ok&&loaded.value.size()==3,"load returns binary value");store.next_fault=p::SecretFault::ReplaceFailed;std::array<std::byte,1> newer{std::byte{9}};check(!store.store("sync.token",newer).ok,"replace failure surfaced");check(store.load("sync.token").value.size()==3,"failed replacement preserves old value");check(store.erase("sync.token").existed,"delete reports existing");check(!store.erase("sync.token").existed,"delete missing is idempotent");check(store.load("sync.token").fault==p::SecretFault::NotFound,"missing is distinct");check(store.store("bad/key",raw).fault==p::SecretFault::InvalidKey,"invalid key refused");check(store.store("empty",{}).fault==p::SecretFault::EmptyValue,"empty value refused");std::vector<std::byte> huge(p::kMaxSecretValueLength+1);check(store.store("huge",huge).fault==p::SecretFault::ValueTooLarge,"oversized value refused");store.next_fault=p::SecretFault::PermissionDenied;check(store.store("sync.token",raw).fault==p::SecretFault::PermissionDenied,"permission failure injected");return squiflow::testing::report();}
