#include <cstdint>
#include <memory>
#include <string>
#include "engine/audit/audit_log.hpp"
#include "engine/records/payload.hpp"
#include "engine/storage/database.hpp"
#include "engine/storage/memory_store.hpp"
#include "engine/sync/outbox.hpp"
#include "modules/agreements/data/repository.hpp"
#include "modules/agreements/module.hpp"
#include "modules/orders/module.hpp"
#include "modules/pricing/module.hpp"
#include "modules/receivables/data/repository.hpp"
#include "modules/receivables/module.hpp"
#include "modules/registry.hpp"
#include "support/check.hpp"
#include "workflows/apply_agreement.hpp"
#include "workflows/cancel_and_reissue.hpp"
#include "workflows/issue_invoice.hpp"
using squiflow::testing::check;using squiflow::testing::section;
namespace e=squiflow::engine;namespace m=squiflow::modules;namespace a=squiflow::modules::agreements;namespace r=squiflow::modules::receivables;namespace p=squiflow::protocol;namespace w=squiflow::workflows;
namespace {
constexpr std::int64_t N=1930000000000LL;std::int64_t now(){return N;}
const std::string Person="b1000000000000000000000000000001",Device="b1000000000000000000000000000002",Party="b2000000000000000000000000000001",Invoice="b3000000000000000000000000000001",Replacement="b3000000000000000000000000000002",Line="b4000000000000000000000000000001",Agreement="b5000000000000000000000000000001",AgLine="b6000000000000000000000000000001",Product="b7000000000000000000000000000001",Application="b8000000000000000000000000000001";
e::Session owner(){e::Session s;s.person=e::record_id_from_string(Person);s.device=e::record_id_from_string(Device);s.is_owner=true;s.rights.grant_all();return s;}
e::Blob applyBody(std::int64_t quantity=1000,std::int64_t rate=500){e::Row x;x.set("invoice_id",e::Value::text(Invoice));x.set("invoice_line_id",e::Value::text(Line));x.set("agreement_id",e::Value::text(Agreement));x.set("agreement_line_id",e::Value::text(AgLine));x.set("expected_quantity_scaled",e::Value::integer(quantity));x.set("expected_current_rate_minor",e::Value::integer(rate));return e::encode_payload(x);}
e::Blob issueBody(){e::Row x;x.set("series",e::Value::text("INV"));x.set("expected_line_count",e::Value::integer(1));x.set("expected_total_minor",e::Value::integer(300));return e::encode_payload(x);}
e::Blob cancelBody(){e::Row x;x.set("replacement_invoice_id",e::Value::text(Replacement));x.set("reason",e::Value::text("customer correction"));x.set("expected_series",e::Value::text("INV"));x.set("expected_number",e::Value::integer(1));x.set("expected_line_count",e::Value::integer(1));x.set("expected_total_minor",e::Value::integer(300));return e::encode_payload(x);}
struct Shop{m::Registry reg{now};std::unique_ptr<e::Database>db;Shop(){reg.add(m::pricing::make_module(now));reg.add(m::orders::make_module(now));reg.add(r::make_module(now));reg.add(a::make_module(now));reg.install_workflow(w::make_apply_agreement(now));reg.install_workflow(w::make_issue_invoice(now));reg.install_workflow(w::make_cancel_and_reissue(now));e::MigrationRunner run{now};reg.collect_migrations(run);db=std::make_unique<e::Database>(std::make_unique<e::MemoryStore>(),std::move(run));db->open();}void seed(std::int64_t quantity=1000,std::int64_t cap=2000){db->write([&](e::Transaction&t){a::Agreement ag;ag.id=Agreement;ag.party_id=Party;ag.state=a::AgreementState::Open;ag.valid_from=N-10000;ag.valid_until=N+10000;ag.created_at=N-20000;ag.created_by=Person;ag.opened_at=N-15000;ag.opened_by=Person;a::data::save_agreement(t,ag);a::AgreementLine al;al.id=AgLine;al.agreement_id=Agreement;al.product_id=Product;al.agreed_name="agreed print";al.rate_minor=300;al.cap_scaled=cap;a::data::save_line(t,al);r::Invoice inv;inv.id=Invoice;inv.party_id=Party;inv.created_at=N-5000;inv.created_by=Person;r::data::save_invoice(t,inv);r::InvoiceLine line;line.id=Line;line.invoice_id=Invoice;line.product_id=Product;line.description="print";line.quantity_scaled=quantity;line.rate_minor=500;line.amount_minor=quantity/2;line.added_at=N-4000;line.added_by=Person;r::data::save_invoice_line(t,line);r::DocumentNumberBlock b;b.id="numbers";b.series="INV";b.device_id=Device;b.first_number=1;b.next_number=1;b.last_number=3;b.assigned_at=N-30000;b.assignment_reference="server";r::data::save_number_block(t,b);});}m::Outcome run(p::OperationId op,const std::string&id,const std::string&key,const e::Blob&body,const e::Session&s=owner(),e::ConnectionState c=e::ConnectionState::Online){m::Call q;q.operation=op;q.record_id=id;q.idempotency_key=key;q.payload=body;return reg.run(*db,q,s,c);}};
std::size_t count(const Shop&s,const std::string&t){std::size_t n=0;s.db->read([&](const e::Store&x){n=x.count(t);});return n;}
}
int main(){
section("apply freezes exact agreement provenance without consuming");{Shop s;s.seed();auto out=s.run(p::OperationId::apply_agreement,Application,"apply",applyBody());check(out.ok&&out.queued,"agreement applied");s.db->read([](const e::Store&x){auto line=r::data::find_invoice_line(x,Line);auto ag=a::data::find_line(x,AgLine);check(line&&line->rate_origin==e::RateOrigin::Agreement&&line->rate_minor==300&&line->amount_minor==300,"agreed rate and amount frozen");check(line&&line->agreement_id==Agreement&&line->agreement_line_id==AgLine&&line->agreement_quantity_scaled==1000,"structured provenance exact");check(ag&&ag->consumed_scaled==0,"draft consumes nothing");check(x.count(a::tables::kConsumption)==0,"no draft usage row");});auto replay=s.run(p::OperationId::apply_agreement,Application,"apply",applyBody());check(replay.ok&&replay.replayed,"same key replay");}
section("issue consumes and cancel releases atomically");{Shop s;s.seed();check(s.run(p::OperationId::apply_agreement,Application,"a",applyBody()).ok,"applied");check(s.run(p::OperationId::issue_invoice,Invoice,"i",issueBody()).ok,"issued");s.db->read([](const e::Store&x){auto ag=a::data::find_line(x,AgLine);auto usage=a::data::find_consumption(x,a::consumption_id(Line,AgLine));check(ag&&ag->consumed_scaled==1000,"issue consumes exact quantity");check(usage&&usage->state==a::ConsumptionState::Active&&usage->invoice_id==Invoice,"active evidence stored");});check(s.run(p::OperationId::cancel_and_reissue,Invoice,"c",cancelBody()).ok,"cancelled");s.db->read([](const e::Store&x){auto ag=a::data::find_line(x,AgLine);auto usage=a::data::find_consumption(x,a::consumption_id(Line,AgLine));auto repl=r::data::lines_for_invoice(x,Replacement);check(ag&&ag->consumed_scaled==0,"cancellation releases exact quantity");check(usage&&usage->state==a::ConsumptionState::Released&&!usage->release_reason.empty(),"release evidence permanent");check(repl.size()==1&&repl[0].agreement_id==Agreement&&repl[0].agreement_line_id==AgLine,"replacement keeps provenance");});}
section("replacement issuance consumes again");{Shop s;s.seed();check(s.run(p::OperationId::apply_agreement,Application,"a2",applyBody()).ok,"applied");check(s.run(p::OperationId::issue_invoice,Invoice,"i2",issueBody()).ok,"original issued");check(s.run(p::OperationId::cancel_and_reissue,Invoice,"c2",cancelBody()).ok,"original released");e::Row replacement_request=e::decode_payload(issueBody());check(s.run(p::OperationId::issue_invoice,Replacement,"r2",e::encode_payload(replacement_request)).ok,"replacement issued");s.db->read([](const e::Store&x){auto ag=a::data::find_line(x,AgLine);auto lines=r::data::lines_for_invoice(x,Replacement);auto usage=a::data::find_consumption(x,a::consumption_id(lines[0].id,AgLine));check(ag&&ag->consumed_scaled==1000,"only active replacement consumes");check(usage&&usage->state==a::ConsumptionState::Active,"replacement usage active");});}
section("cap and stale evidence fail without partial writes");{Shop over;over.seed(3000,2000);check(over.run(p::OperationId::apply_agreement,Application,"oa",applyBody(3000)).ok,"over-cap draft may be staged");e::Row issue=e::decode_payload(issueBody());issue.set("expected_total_minor",e::Value::integer(900));check(!over.run(p::OperationId::issue_invoice,Invoice,"oi",e::encode_payload(issue)).ok,"over-cap issue refused");over.db->read([](const e::Store&x){auto ag=a::data::find_line(x,AgLine);auto inv=r::data::find_invoice(x,Invoice);auto b=r::data::find_number_block(x,"numbers");check(ag&&ag->consumed_scaled==0&&inv&&inv->state==e::DocumentState::Draft,"cap and invoice rollback");check(b&&b->next_number==1&&!b->exhausted,"number remains available");});check(count(over,a::tables::kConsumption)==0&&count(over,e::AuditLog::table_name())==1,"failed issue adds no usage or audit");Shop stale;stale.seed();check(!stale.run(p::OperationId::apply_agreement,Application,"stale",applyBody(999)).ok,"stale quantity refused");check(count(stale,e::AuditLog::table_name())==0&&count(stale,e::Outbox::table_name())==0,"stale application writes nothing");}
section("state customer product rights and malformed payload fail closed");{Shop s;s.seed();e::Session denied=owner();denied.rights.revoke(p::RightId::right_agreement_read);check(!s.run(p::OperationId::apply_agreement,Application,"d",applyBody(),denied).ok,"agreement right required");check(!s.run(p::OperationId::apply_agreement,Application,"bad",e::Blob{1,2,3}).ok,"malformed refused");s.db->write([](e::Transaction&t){auto ag=a::data::find_agreement(t,Agreement);ag->state=a::AgreementState::Closed;ag->closed_at=N;ag->closed_by=Person;ag->close_reason="done";a::data::save_agreement(t,*ag);});check(!s.run(p::OperationId::apply_agreement,Application,"closed",applyBody()).ok,"closed agreement refused");check(count(s,a::tables::kConsumption)==0,"refusals consume nothing");}
return squiflow::testing::report();}
