#include <cstdint>
#include <memory>
#include <string>
#include "engine/audit/audit_log.hpp"
#include "engine/records/payload.hpp"
#include "engine/storage/database.hpp"
#include "engine/storage/memory_store.hpp"
#include "engine/sync/outbox.hpp"
#include "modules/orders/module.hpp"
#include "modules/agreements/module.hpp"
#include "modules/pricing/module.hpp"
#include "modules/receivables/data/repository.hpp"
#include "modules/receivables/module.hpp"
#include "modules/registry.hpp"
#include "support/check.hpp"
#include "workflows/cancel_and_reissue.hpp"
#include "workflows/issue_invoice.hpp"
using squiflow::testing::check; using squiflow::testing::section;
namespace e=squiflow::engine; namespace m=squiflow::modules; namespace r=squiflow::modules::receivables; namespace p=squiflow::protocol; namespace w=squiflow::workflows;
namespace {
constexpr std::int64_t N=1910000000000LL; std::int64_t now(){return N;}
const std::string Person="91000000000000000000000000000001",Device="91000000000000000000000000000002",Party="92000000000000000000000000000001",Source="93000000000000000000000000000001",Repl="93000000000000000000000000000002",Repl2="93000000000000000000000000000003",Other="93000000000000000000000000000004",L1="94000000000000000000000000000001",L2="94000000000000000000000000000002",Pay="95000000000000000000000000000001",Alloc="96000000000000000000000000000001";
e::Session owner(){e::Session s;s.person=e::record_id_from_string(Person);s.device=e::record_id_from_string(Device);s.is_owner=true;s.rights.grant_all();return s;}
e::Blob cancelBody(const std::string&r=Repl,const std::string&reason="wrong quantity",std::int64_t num=100,std::int64_t cnt=2,std::int64_t total=3000){e::Row x;x.set("replacement_invoice_id",e::Value::text(r));x.set("reason",e::Value::text(reason));x.set("expected_series",e::Value::text("INV"));x.set("expected_number",e::Value::integer(num));x.set("expected_line_count",e::Value::integer(cnt));x.set("expected_total_minor",e::Value::integer(total));return e::encode_payload(x);}
e::Blob issueBody(){e::Row x;x.set("series",e::Value::text("INV"));x.set("expected_line_count",e::Value::integer(2));x.set("expected_total_minor",e::Value::integer(3000));return e::encode_payload(x);}
struct Shop{m::Registry reg{now};std::unique_ptr<e::Database>db;Shop(){reg.add(m::pricing::make_module(now));reg.add(m::orders::make_module(now));reg.add(r::make_module(now));reg.add(m::agreements::make_module(now));reg.install_workflow(w::make_issue_invoice(now));reg.install_workflow(w::make_cancel_and_reissue(now));e::MigrationRunner run{now};reg.collect_migrations(run);db=std::make_unique<e::Database>(std::make_unique<e::MemoryStore>(),std::move(run));db->open();}
void seed(const std::string&id=Source,e::DocumentState state=e::DocumentState::Issued,std::uint64_t num=100,bool lines=true){db->write([&](e::Transaction&t){r::Invoice v;v.id=id;v.party_id=Party;v.state=state;v.created_at=N-50000;v.created_by=Person;v.due_at=N+86400000;v.note="copy";if(state!=e::DocumentState::Draft){v.number_series="INV";v.number=num;v.issued_at=N-40000;v.issued_by=Person;}r::data::save_invoice(t,v);if(!lines)return;r::InvoiceLine a;a.id=id==Source?L1:id.substr(0,31)+"a";a.invoice_id=id;a.description="unicode \xE2\x9C\x93";a.quantity_scaled=1000;a.rate_minor=500;a.amount_minor=500;a.added_at=N-39000;a.added_by=Person;r::data::save_invoice_line(t,a);r::InvoiceLine b;b.id=id==Source?L2:id.substr(0,31)+"b";b.invoice_id=id;b.position=1;b.description=std::string(2048,'x');b.quantity_scaled=2000;b.rate_minor=1250;b.amount_minor=2500;b.rate_origin=e::RateOrigin::ManualOverride;b.rate_reason="approved";b.added_at=N-38000;b.added_by=Person;r::data::save_invoice_line(t,b);});}
void payment(){db->write([](e::Transaction&t){r::Payment q;q.id=Pay;q.party_id=Party;q.amount_minor=4000;q.paid_at=N-30000;q.method="cash";q.receipt_series="R";q.receipt_number=1;q.recorded_at=N-29000;q.recorded_by=Person;r::data::save_payment(t,q);r::PaymentAllocation a;a.id=Alloc;a.payment_id=Pay;a.target={p::ModuleId::receivables,e::record_id_from_string(Source)};a.amount_minor=1200;a.allocated_at=N-20000;a.allocated_by=Person;r::data::save_allocation(t,a);});}
void block(std::uint64_t n){db->write([&](e::Transaction&t){r::DocumentNumberBlock b;b.id="block";b.series="INV";b.device_id=Device;b.first_number=n;b.next_number=n;b.last_number=n+1;b.assigned_at=N-100000;b.assignment_reference="server";r::data::save_number_block(t,b);});}
m::Outcome run(p::OperationId op,const std::string&id,const std::string&key,const e::Blob&body,const e::Session&s=owner(),e::ConnectionState c=e::ConnectionState::Online){m::Call q;q.operation=op;q.record_id=id;q.idempotency_key=key;q.payload=body;return reg.run(*db,q,s,c);}m::Outcome cancel(const std::string&key,const e::Blob&b=cancelBody(),const e::Session&s=owner(),e::ConnectionState c=e::ConnectionState::Online){return run(p::OperationId::cancel_and_reissue,Source,key,b,s,c);}};
std::size_t count(const Shop&s,const std::string&t){std::size_t n=0;s.db->read([&](const e::Store&x){n=x.count(t);});return n;}
}
int main(){
section("atomic cancel clone release and replay");{Shop s;s.seed();s.payment();auto o=s.cancel("c1");check(o.ok&&o.queued&&!o.replayed,"cancel succeeds online");s.db->read([](const e::Store&x){auto a=r::data::find_invoice(x,Source),b=r::data::find_invoice(x,Repl);check(a&&a->state==e::DocumentState::Cancelled&&a->number==100&&a->cancel_reason=="wrong quantity","original retains numbered cancellation evidence");check(b&&b->state==e::DocumentState::Draft&&b->number==0&&b->replaces_invoice_id==Source,"linked unnumbered draft created");check(b&&b->party_id==Party&&b->note=="copy"&&b->due_at==N+86400000,"header copied");auto lines=r::data::lines_for_invoice(x,Repl);check(lines.size()==2&&lines[0].id==w::replacement_invoice_line_id(Repl,L1)&&lines[1].id==w::replacement_invoice_line_id(Repl,L2),"lines receive deterministic identities");check(lines.size()==2&&lines[1].rate_minor==1250&&lines[1].amount_minor==2500&&lines[1].rate_reason=="approved","frozen rates copied without repricing");auto al=r::data::find_allocation(x,Alloc);check(al&&al->state==r::AllocationState::Released&&al->released_at==N,"allocation released with evidence");auto pay=r::data::find_payment(x,Pay);auto free=r::unallocated_amount(*pay,r::data::allocations_for_payment(x,Pay));check(free.ok&&free.value.minor==4000,"money becomes unallocated, not reallocated");check(x.find(e::AuditLog::table_name(),"c1").has_value()&&x.find(e::Outbox::table_name(),"c1").has_value(),"audit and outbox commit");});auto replay=s.cancel("c1");check(replay.ok&&replay.replayed,"same-key replay");check(!s.cancel("other").ok,"second active replacement refused");check(count(s,r::tables::kInvoice)==2,"no duplicate invoice");}
section("issuing replacement completes permanent pair");{Shop s;s.seed();s.block(200);check(s.cancel("c2").ok,"draft created");check(s.run(p::OperationId::issue_invoice,Repl,"i2",issueBody()).ok,"replacement issued");s.db->read([](const e::Store&x){auto a=r::data::find_invoice(x,Source),b=r::data::find_invoice(x,Repl);check(a&&a->state==e::DocumentState::Replaced&&a->replacement_invoice_id==Repl&&a->number==100,"source points to replacement");check(b&&b->state==e::DocumentState::Issued&&b->replaces_invoice_id==Source&&b->number==200,"replacement points back and gets new number");auto n=r::data::find_number_block(x,"block");check(n&&n->next_number==201,"one replacement number consumed");});}
section("discard retry keeps original reason");{Shop s;s.seed();check(s.cancel("first").ok,"first draft");check(s.run(p::OperationId::invoice_draft_discard,Repl,"discard",{}).ok,"discard replacement");check(s.cancel("retry",cancelBody(Repl2)).ok,"retry after discard");s.db->read([](const e::Store&x){auto a=r::data::find_invoice(x,Source),old=r::data::find_invoice(x,Repl),next=r::data::find_invoice(x,Repl2);check(a&&a->state==e::DocumentState::Cancelled&&a->cancel_reason=="wrong quantity","cancellation immutable");check(old&&old->state==e::DocumentState::Discarded&&next&&next->state==e::DocumentState::Draft,"old attempt retained and next active");});check(!s.cancel("rewrite",cancelBody("93000000000000000000000000000005","new reason")).ok,"reason rewrite refused");}
section("rights online stale malformed and state gates");{Shop s;s.seed();e::Session d=owner();d.rights.revoke(p::RightId::right_invoice_cancel);check(!s.cancel("denied",cancelBody(),d).ok,"right required");check(!s.cancel("offline",cancelBody(),owner(),e::ConnectionState::Offline).ok,"online only");check(!s.cancel("num",cancelBody(Repl,"wrong quantity",99)).ok,"stale number");check(!s.cancel("cnt",cancelBody(Repl,"wrong quantity",100,1)).ok,"stale count");check(!s.cancel("tot",cancelBody(Repl,"wrong quantity",100,2,2999)).ok,"stale total");check(!s.cancel("self",cancelBody(Source)).ok,"self link refused");check(!s.cancel("bad",e::Blob{1,2,3}).ok,"bad payload");check(count(s,e::AuditLog::table_name())==0&&count(s,e::Outbox::table_name())==0,"refusals have no evidence rows");Shop draft;draft.seed(Source,e::DocumentState::Draft,0);check(!draft.cancel("draft").ok,"draft source refused");Shop empty;empty.seed(Source,e::DocumentState::Issued,100,false);check(!empty.cancel("empty").ok,"empty source refused");}
section("late collision rolls back source allocation clone and evidence");{Shop s;s.seed();s.payment();s.db->write([](e::Transaction&t){r::InvoiceLine z;z.id=w::replacement_invoice_line_id(Repl,L2);z.invoice_id=Other;z.description="collision";z.quantity_scaled=1000;z.rate_minor=1;z.amount_minor=1;z.added_at=N-1;z.added_by=Person;r::data::save_invoice_line(t,z);});check(!s.cancel("late").ok,"later line collision refused");s.db->read([](const e::Store&x){auto a=r::data::find_invoice(x,Source);auto al=r::data::find_allocation(x,Alloc);check(a&&a->state==e::DocumentState::Issued&&a->cancelled_at==0,"source rollback");check(al&&al->state==r::AllocationState::Active,"allocation rollback");check(!r::data::find_invoice(x,Repl),"clone rollback");check(!r::data::find_invoice_line(x,w::replacement_invoice_line_id(Repl,L1)),"earlier line rollback");});check(count(s,e::AuditLog::table_name())==0&&count(s,e::Outbox::table_name())==0,"late failure no audit/outbox");}
section("failed replacement issue leaves source waiting and number free");{Shop s;s.seed();s.seed(Other,e::DocumentState::Issued,300);s.block(300);check(s.cancel("before").ok,"waiting draft created");check(!s.run(p::OperationId::issue_invoice,Repl,"fail",issueBody()).ok,"duplicate number refused");s.db->read([](const e::Store&x){auto a=r::data::find_invoice(x,Source),b=r::data::find_invoice(x,Repl);auto n=r::data::find_number_block(x,"block");check(a&&a->state==e::DocumentState::Cancelled&&a->replacement_invoice_id.empty(),"source still waiting");check(b&&b->state==e::DocumentState::Draft&&b->number==0,"draft remains editable");check(n&&n->next_number==300,"number rollback");});}
return squiflow::testing::report();}
