#include <cstdint>
#include <limits>
#include <memory>
#include <string>
#include "engine/audit/audit_log.hpp"
#include "engine/records/payload.hpp"
#include "engine/storage/database.hpp"
#include "engine/storage/memory_store.hpp"
#include "engine/sync/outbox.hpp"
#include "modules/parties/data/repository.hpp"
#include "modules/parties/module.hpp"
#include "modules/pricing/module.hpp"
#include "modules/receivables/data/repository.hpp"
#include "modules/receivables/module.hpp"
#include "modules/registry.hpp"
#include "support/check.hpp"
#include "workflows/take_payment.hpp"
using squiflow::testing::check; using squiflow::testing::section;
namespace e=squiflow::engine; namespace m=squiflow::modules; namespace p=squiflow::protocol; namespace party=squiflow::modules::parties; namespace r=squiflow::modules::receivables; namespace w=squiflow::workflows;
namespace {
constexpr std::int64_t Now=1920000000000LL; std::int64_t now(){return Now;}
const std::string Person="a1000000000000000000000000000001",Device="a1000000000000000000000000000002",Customer="a2000000000000000000000000000001",Supplier="a2000000000000000000000000000002",Archived="a2000000000000000000000000000003",Payment="a3000000000000000000000000000001",Invoice="a4000000000000000000000000000001",Line="a5000000000000000000000000000001",Allocation="a6000000000000000000000000000001";
e::Session owner(){e::Session s;s.person=e::record_id_from_string(Person);s.device=e::record_id_from_string(Device);s.is_owner=true;s.rights.grant_all();return s;}
e::Blob body(const std::string&method="cash",std::int64_t amount=5000,std::int64_t paid=Now-1000,const std::string&ref={},const std::string&series={},std::int64_t number=0){e::Row x;x.set("party_id",e::Value::text(Customer));x.set("amount_minor",e::Value::integer(amount));x.set("paid_at",e::Value::integer(paid));x.set("method",e::Value::text(method));if(!ref.empty())x.set("external_reference",e::Value::text(ref));x.set("note",e::Value::text("optional note"));if(!series.empty())x.set("receipt_series",e::Value::text(series));if(number!=0)x.set("receipt_number",e::Value::integer(number));return e::encode_payload(x);}
e::Blob allocBody(std::int64_t amount=2000){e::Row x;x.set("action",e::Value::text("allocate"));x.set("allocation_id",e::Value::text(Allocation));x.set("target_module",e::Value::text("invoice"));x.set("target_id",e::Value::text(Invoice));x.set("amount_minor",e::Value::integer(amount));return e::encode_payload(x);}
struct Shop{m::Registry reg{now};std::unique_ptr<e::Database>db;Shop(){reg.add(party::make_module(now));reg.add(m::pricing::make_module(now));reg.add(r::make_module(now));reg.install_workflow(w::make_take_payment(now));e::MigrationRunner run{now};reg.collect_migrations(run);db=std::make_unique<e::Database>(std::make_unique<e::MemoryStore>(),std::move(run));db->open();seedParty(Customer,true,false);seedParty(Supplier,false,false);seedParty(Archived,true,true);}void seedParty(const std::string&id,bool customer,bool archived){db->write([&](e::Transaction&t){party::Party x;x.id=id;x.display_name=id==Customer?"Unicode customer \xE2\x9C\x93":"Other party";x.is_customer=customer;x.is_supplier=!customer;x.archived=archived;x.created_at=Now-10000;x.updated_at=Now-10000;x.created_by=Person;x.updated_by=Person;party::data::save_party(t,x);});}void invoice(){db->write([](e::Transaction&t){r::Invoice i;i.id=Invoice;i.party_id=Customer;i.state=e::DocumentState::Issued;i.number_series="INV";i.number=1;i.created_at=Now-9000;i.created_by=Person;i.issued_at=Now-8000;i.issued_by=Person;r::data::save_invoice(t,i);r::InvoiceLine l;l.id=Line;l.invoice_id=Invoice;l.description="work";l.quantity_scaled=1000;l.rate_minor=5000;l.amount_minor=5000;l.added_at=Now-7000;l.added_by=Person;r::data::save_invoice_line(t,l);});}m::Outcome run(p::OperationId op,const std::string&id,const std::string&key,const e::Blob&payload,const e::Session&s=owner(),e::ConnectionState c=e::ConnectionState::Online){m::Call q;q.operation=op;q.record_id=id;q.idempotency_key=key;q.payload=payload;return reg.run(*db,q,s,c);}m::Outcome take(const std::string&key,const e::Blob&b=body(),const e::Session&s=owner(),e::ConnectionState c=e::ConnectionState::Online){return run(p::OperationId::take_payment,Payment,key,b,s,c);}};
std::size_t count(const Shop&s,const std::string&t){std::size_t n=0;s.db->read([&](const e::Store&x){n=x.count(t);});return n;}
e::Blob withParty(const e::Blob&b,const std::string&id){e::Row x=e::decode_payload(b);x.set("party_id",e::Value::text(id));return e::encode_payload(x);}
}
int main(){
section("simple cash payment needs no tracking or receipt number");{Shop s;auto out=s.take("cash");check(out.ok&&out.queued&&!out.replayed,"cash payment recorded");s.db->read([](const e::Store&x){auto q=r::data::find_payment(x,Payment);check(q&&q->party_id==Customer&&q->amount_minor==5000,"customer credit and amount retained");check(q&&q->method=="cash"&&q->external_reference.empty(),"simple method needs no tracking");check(q&&q->receipt_series.empty()&&q->receipt_number==0,"receipt evidence optional");check(q&&q->recorded_at==Now&&q->recorded_by==Person,"system evidence retained");auto free=r::unallocated_amount(*q,r::data::allocations_for_payment(x,Payment));check(free.ok&&free.value.minor==5000,"all money starts unallocated");check(x.find(e::AuditLog::table_name(),"cash").has_value()&&x.find(e::Outbox::table_name(),"cash").has_value(),"audit and outbox committed");});auto replay=s.take("cash");check(replay.ok&&replay.replayed,"same key replays");check(count(s,r::tables::kPayment)==1,"no duplicate money");}
section("bank cheque and handwritten references are optional free text");{for(const auto& sample: {std::pair{"bank","BANK-77"},std::pair{"cheque","CHQ-9"},std::pair{"mobile wallet","TXN \xE2\x9C\x93"}}){Shop s;auto out=s.take(sample.first,body(sample.first,5000,Now-1000,sample.second));check(out.ok,"payment means accepted");s.db->read([&](const e::Store&x){auto q=r::data::find_payment(x,Payment);check(q&&q->method==sample.first&&q->external_reference==sample.second,"optional reference preserved exactly");});}}
section("manual receipt pair is accepted but never generated");{Shop s;check(s.take("receipt",body("cash",5000,Now-1,"","BOOK",41)).ok,"manual receipt evidence optional");s.db->read([](const e::Store&x){auto q=r::data::find_payment(x,Payment);check(q&&q->receipt_series=="BOOK"&&q->receipt_number==41,"entered receipt pair preserved");});Shop missingNumber;check(!missingNumber.take("series-only",body("cash",5000,Now-1,"","BOOK",0)).ok,"series without number refused");Shop missingSeries;check(!missingSeries.take("number-only",body("cash",5000,Now-1,"","",41)).ok,"number without series refused");}
section("manual allocation stays separate and easy");{Shop s;s.invoice();check(s.take("take").ok,"payment recorded first");check(s.run(p::OperationId::payment_allocate,Payment,"allocate",allocBody()).ok,"explicit allocation succeeds");s.db->read([](const e::Store&x){auto q=r::data::find_payment(x,Payment);auto a=r::data::find_allocation(x,Allocation);check(a&&a->amount_minor==2000&&a->state==r::AllocationState::Active,"manual amount retained");auto free=r::unallocated_amount(*q,r::data::allocations_for_payment(x,Payment));check(free.ok&&free.value.minor==3000,"remainder stays unallocated");auto due=r::data::outstanding_for_invoice(x,Invoice);check(due.ok&&due.value.minor==3000,"invoice outstanding reconciles");});check(!s.run(p::OperationId::payment_allocate,Payment,"over",allocBody(4000)).ok,"over-allocation refused");}
section("statements and printable payment records support unnumbered money");{Shop s;check(s.take("plain").ok,"unnumbered payment recorded");auto printed=s.run(p::OperationId::document_print,"","print",[]{e::Row x;x.set("document_type",e::Value::text("receipt"));x.set("document_id",e::Value::text(Payment));return e::encode_payload(x);}());check(printed.ok&&printed.rows.size()==1&&printed.rows[0].get("receipt_number").integer_or(-1)==0,"unnumbered payment remains printable");}
section("authorization offline and validation boundaries");{Shop staff; e::Session allowed=owner();allowed.is_owner=false;check(staff.take("offline",body(),allowed,e::ConnectionState::Offline).ok,"staff offline exception works");Shop denied;e::Session no=owner();no.rights.revoke(p::RightId::right_payment_record);check(!denied.take("denied",body(),no).ok,"record right required");Shop supplier;check(!supplier.take("supplier",withParty(body(),Supplier)).ok,"supplier-only party refused");Shop archived;check(!archived.take("archived",withParty(body(),Archived)).ok,"archived customer refused");Shop future;check(!future.take("future",body("cash",5000,Now+1)).ok,"future payment time refused");Shop zero;check(!zero.take("zero",body("cash",0)).ok,"zero refused");Shop negative;check(!negative.take("negative",body("cash",-1)).ok,"negative refused");Shop blank;check(!blank.take("blank",body(" ")).ok,"blank method refused");Shop bad;check(!bad.take("bad",e::Blob{1,2,3}).ok,"malformed payload refused");check(count(bad,r::tables::kPayment)==0&&count(bad,e::AuditLog::table_name())==0&&count(bad,e::Outbox::table_name())==0,"failure writes nothing");}
section("identity collision and maximum amount remain safe");{Shop s;check(s.take("first").ok,"first payment");check(!s.take("different").ok,"different-key identity collision refused");check(count(s,r::tables::kPayment)==1,"collision duplicates nothing");Shop max;check(max.take("max",body("bank",std::numeric_limits<std::int64_t>::max())).ok,"largest positive amount retained");max.db->read([](const e::Store&x){auto q=r::data::find_payment(x,Payment);check(q&&q->amount_minor==std::numeric_limits<std::int64_t>::max(),"maximum exact");});}
return squiflow::testing::report();}
