#include <atomic>
#include <cstdint>
#include <functional>
#include <memory>
#include <set>
#include <string>
#include <thread>
#include <vector>
#include <squiflow/protocol/workflow_table.hpp>
#include "engine/audit/audit_log.hpp"
#include "engine/storage/database.hpp"
#include "engine/storage/memory_store.hpp"
#include "engine/sync/outbox.hpp"
#include "modules/registry.hpp"
#include "support/check.hpp"
using squiflow::testing::check; using squiflow::testing::section;
namespace engine=squiflow::engine; namespace modules=squiflow::modules; namespace protocol=squiflow::protocol; namespace workflows=squiflow::workflows;
namespace {
std::int64_t g_now=1'800'000'000'000; std::int64_t now(){return g_now;} engine::RecordId id(std::uint64_t n){return {9,n};}
class Shell final:public modules::Module{public:Shell(protocol::ModuleId m,int n,std::string t={}):m_(m),n_(n),t_(std::move(t)){} protocol::ModuleId id()const noexcept override{return m_;} std::vector<engine::Migration> migrations()const override{if(n_==0)return{};engine::Migration x;x.number=n_;x.name=std::string(protocol::module_name(m_));auto t=t_;x.schema=[t](engine::Store&s){if(!t.empty())s.define_table(t,"id");};return{x};}void install(modules::Registry&)override{}private:protocol::ModuleId m_;int n_;std::string t_;};
class Trespass final:public modules::Module{public:protocol::ModuleId id()const noexcept override{return protocol::ModuleId::receivables;}std::vector<engine::Migration> migrations()const override{return{};}void install(modules::Registry&r)override{r.on_write(protocol::OperationId::take_payment,[](engine::Transaction&,const modules::Call&){});}};
engine::Session owner(){engine::Session s;s.person=id(1);s.device=id(2);s.is_owner=true;s.rights.grant_all();return s;}
bool error(const std::function<void()>&f){try{f();}catch(const modules::RegistryError&){return true;}return false;}
workflows::WorkflowDefinition payment(workflows::WorkflowHandler h){return{protocol::OperationId::take_payment,{protocol::ModuleId::receivables,protocol::ModuleId::parties},std::move(h)};}
void put(engine::Transaction&t,const std::string&table,const std::string&key){engine::Row r;r.set("id",engine::Value::text(key));t.insert(table,r);}
modules::Call call(std::string key){modules::Call c;c.operation=protocol::OperationId::take_payment;c.record_id="payment";c.idempotency_key=std::move(key);return c;}
struct Fixture{modules::Registry registry{now};std::unique_ptr<engine::Database> db;Fixture(){registry.add(std::make_unique<Shell>(protocol::ModuleId::parties,11,"left"));registry.add(std::make_unique<Shell>(protocol::ModuleId::receivables,15,"right"));}void open(){engine::MigrationRunner r{now};registry.collect_migrations(r);db=std::make_unique<engine::Database>(std::make_unique<engine::MemoryStore>(),std::move(r));db->open();}std::size_t count(const std::string&t)const{std::size_t n=0;db->read([&](const engine::Store&s){n=s.count(t);});return n;}};
}
int main(){
section("exact workflow protocol classification");{std::set<protocol::OperationId>s;for(auto op:protocol::workflow_operations()){check(protocol::is_workflow_operation(op),"listed workflow classifies");check(s.insert(op).second,"workflow id is unique");}check(s.size()==8,"exactly eight workflows");check(!protocol::is_workflow_operation(protocol::OperationId::party_create),"ordinary operation excluded");check(!protocol::is_workflow_operation(protocol::OperationId::Count),"invalid sentinel safe");}
section("registration ownership and exact requirements");{modules::Registry trespass{now};check(error([&]{trespass.add(std::make_unique<Trespass>());}),"modules cannot own workflows");Fixture f;auto good=[](engine::Transaction&,const modules::Call&){return workflows::WorkflowResult{{protocol::ModuleId::receivables,id(3)},"paid"};};check(error([&]{f.registry.install_workflow({protocol::OperationId::party_create,{protocol::ModuleId::parties},good});}),"ordinary op cannot be workflow");check(error([&]{f.registry.install_workflow(payment({}));}),"empty handler refused");check(error([&]{f.registry.install_workflow({protocol::OperationId::take_payment,{},good});}),"empty requirements refused");check(error([&]{f.registry.install_workflow({protocol::OperationId::take_payment,{protocol::ModuleId::receivables},good});}),"missing requirement refused");check(error([&]{f.registry.install_workflow({protocol::OperationId::take_payment,{protocol::ModuleId::receivables,protocol::ModuleId::parties,protocol::ModuleId::pricing},good});}),"invented requirement refused");f.registry.install_workflow(payment(good));check(f.registry.handled(protocol::OperationId::take_payment),"valid workflow handled");check(error([&]{f.registry.install_workflow(payment(good));}),"duplicate refused");}
section("one transaction audit outbox and replay");{Fixture f;std::atomic<int> entered{0};f.registry.install_workflow(payment([&](engine::Transaction&t,const modules::Call&){++entered;put(t,"left","a");put(t,"right","b");return workflows::WorkflowResult{{protocol::ModuleId::receivables,id(44)},"Recorded payment"};}));f.open();auto first=f.registry.run(*f.db,call("key"),owner(),engine::ConnectionState::Offline);check(first.ok&&first.queued&&!first.replayed,"success commits and queues");check(entered==1,"handler once");check(f.count("left")==1&&f.count("right")==1,"both business rows");check(f.count(engine::AuditLog::table_name())==1,"one audit");check(f.count(engine::Outbox::table_name())==1,"one outbox");f.db->read([&](const engine::Store&s){auto a=engine::find_audit(s,"key");check(a.has_value(),"audit found");check(a&&a->person==id(1)&&a->device==id(2),"actor exact");check(a&&a->at.ms==g_now,"time exact");check(a&&a->subject==engine::Reference{protocol::ModuleId::receivables,id(44)},"subject exact");check(a&&a->detail=="Recorded payment","detail exact");});auto replay=f.registry.run(*f.db,call("key"),owner(),engine::ConnectionState::Online);check(replay.ok&&replay.replayed&&!replay.queued,"retry replays");check(entered==1,"replay skips handler");check(f.count("left")==1&&f.count(engine::AuditLog::table_name())==1&&f.count(engine::Outbox::table_name())==1,"replay duplicates nothing");}
section("partial failure and malformed audit roll back");{Fixture f;bool fail=true;f.registry.install_workflow(payment([&](engine::Transaction&t,const modules::Call&){put(t,"left",fail?"bad":"good");if(fail)throw modules::RuleViolation("unbalanced");return workflows::WorkflowResult{{protocol::ModuleId::receivables,id(5)},"recovered"};}));f.open();auto bad=f.registry.run(*f.db,call("bad"),owner(),engine::ConnectionState::Online);check(!bad.ok&&bad.error=="unbalanced","business refusal returned");check(f.count("left")==0&&f.count(engine::AuditLog::table_name())==0&&f.count(engine::Outbox::table_name())==0,"partial refusal rolls all back");fail=false;check(f.registry.run(*f.db,call("good"),owner(),engine::ConnectionState::Online).ok,"writer recovers");Fixture malformed;malformed.registry.install_workflow(payment([](engine::Transaction&t,const modules::Call&){put(t,"left","x");return workflows::WorkflowResult{{protocol::ModuleId::receivables,id(6)},"   "};}));malformed.open();check(!malformed.registry.run(*malformed.db,call("blank"),owner(),engine::ConnectionState::Online).ok,"blank audit refused");check(malformed.count("left")==0&&malformed.count(engine::AuditLog::table_name())==0&&malformed.count(engine::Outbox::table_name())==0,"bad audit rolls back");}
section("concurrent duplicates execute once");{Fixture f;std::atomic<int> entered{0};f.registry.install_workflow(payment([&](engine::Transaction&t,const modules::Call&){++entered;put(t,"left","one");return workflows::WorkflowResult{{protocol::ModuleId::receivables,id(7)},"once"};}));f.open();modules::Outcome a,b;std::thread x([&]{a=f.registry.run(*f.db,call("same"),owner(),engine::ConnectionState::Online);});std::thread y([&]{b=f.registry.run(*f.db,call("same"),owner(),engine::ConnectionState::Online);});x.join();y.join();check(a.ok&&b.ok,"both concurrent calls succeed");check(a.replayed!=b.replayed,"exactly one replay");check(entered==1,"concurrent handler once");check(f.count("left")==1&&f.count(engine::AuditLog::table_name())==1&&f.count(engine::Outbox::table_name())==1,"one complete result");}
section("migration 21 upgrades only through 22");{engine::MemoryStore store;engine::MigrationRunner old{now};old.add({1,"engine tables",[](engine::Store&s){engine::Outbox::define(s);engine::Cursor::define(s);engine::ConflictLog::define(s);},{}});old.add({21,"sourcing",[](engine::Store&){},{}});check(old.run(store).version==21,"old store at 21");modules::Registry r{now};r.add(std::make_unique<Shell>(protocol::ModuleId::sourcing,21));engine::MigrationRunner current{now};r.collect_migrations(current);auto up=current.run(store);check(up.applied==std::vector<int>{22},"only 22 applied");check(up.version==22,"current at 22");check(current.run(store).already_current,"reopen current");check(store.count(engine::AuditLog::table_name())==0,"audit table empty");}
return squiflow::testing::report();}
