#include "shell/document_render_qt.hpp"
#if defined(SQUIFLOW_WITH_QT)
#include <QFile>
#include <QPdfWriter>
#include <QPainter>
#include <QSaveFile>
#include <QTemporaryFile>
#include <QTextDocument>
namespace squiflow::shell{DocumentRenderQt::DocumentRenderQt(QString p):prefix_(std::move(p)){}app::Result<QByteArray,PresentationError> DocumentRenderQt::render(const PreparedDocumentSnapshot&s)const{auto v=validate_document_snapshot(s);if(!v)return app::Result<QByteArray,PresentationError>::failure(v.error());QFile f(prefix_+"/"+QString::fromStdString(document_template_name(s.kind)));if(!f.open(QIODevice::ReadOnly))return app::Result<QByteArray,PresentationError>::failure({PresentationErrorCode::MissingTemplate,"document.error.template",{}});QString h=QString::fromUtf8(f.readAll());auto esc=[](const std::string&x){return QString::fromStdString(x).toHtmlEscaped();};QString rows;for(auto&l:s.lines)rows+="<tr><td>"+esc(l.description)+"</td><td>"+esc(l.quantity)+"</td><td>"+esc(l.unit_price)+"</td><td>"+esc(l.amount)+"</td></tr>";h.replace("{{title}}",esc(s.title)).replace("{{party}}",esc(s.party)).replace("{{lines}}",rows).replace("{{total}}",esc(s.total));QTemporaryFile tmp;if(!tmp.open())return app::Result<QByteArray,PresentationError>::failure({PresentationErrorCode::RenderFailed,"document.error.render",{}});QString path=tmp.fileName();tmp.close();{QPdfWriter pdf(path);QPainter p(&pdf);if(!p.isActive())return app::Result<QByteArray,PresentationError>::failure({PresentationErrorCode::RenderFailed,"document.error.render",{}});QTextDocument d;d.setHtml(h);d.setTextWidth(pdf.width());d.drawContents(&p);p.end();}QFile out(path);if(!out.open(QIODevice::ReadOnly))return app::Result<QByteArray,PresentationError>::failure({PresentationErrorCode::RenderFailed,"document.error.render",{}});auto bytes=out.readAll();if(!bytes.startsWith("%PDF-"))return app::Result<QByteArray,PresentationError>::failure({PresentationErrorCode::RenderFailed,"document.error.render",{}});return app::Result<QByteArray,PresentationError>::success(bytes);}app::Result<void,PresentationError> DocumentRenderQt::save(const PreparedDocumentSnapshot&s,const QString&path)const{auto x=render(s);if(!x)return app::Result<void,PresentationError>::failure(x.error());QSaveFile f(path);if(!f.open(QIODevice::WriteOnly)||f.write(x.value())!=x.value().size()||!f.commit())return app::Result<void,PresentationError>::failure({PresentationErrorCode::WriteFailed,"document.error.save",{}});return app::Result<void,PresentationError>::success();}}
#endif
