#include "shell/form_bridge.hpp"
#include <algorithm>
#include <charconv>
#include <limits>
#include <stdexcept>
namespace squiflow::shell{
std::string domain_error_message(app::DomainErrorCode c){switch(c){case app::DomainErrorCode::NotFound:return "form.error.not_found";case app::DomainErrorCode::Unauthorized:return "form.error.unauthorized";case app::DomainErrorCode::ValidationFailed:return "form.error.validation";case app::DomainErrorCode::Conflict:return "form.error.conflict";case app::DomainErrorCode::Offline:return "form.error.offline";case app::DomainErrorCode::Timeout:return "form.error.timeout";case app::DomainErrorCode::Cancelled:return "form.error.cancelled";case app::DomainErrorCode::InvalidContext:return "form.error.invalid_context";}return "form.error.invalid_context";}
PresentedDomainError present_domain_error(const app::DomainError&e){return {e.message_key.empty()?domain_error_message(e.code):e.message_key,e.field,app::is_retryable(e.code)};}
FormBridge::FormBridge(std::vector<FormFieldSpec> f,app::RequestContext c):fields_(std::move(f)),context_(std::move(c)){if(fields_.empty()||fields_.size()>64)throw std::invalid_argument("bounded form schema required");for(const auto&x:fields_){if(x.id.empty()||x.id.size()>64||x.label_key.empty()||std::any_of(values_.begin(),values_.end(),[&](const auto&v){return v.id==x.id;}))throw std::invalid_argument("invalid form field");values_.push_back({x.id,{}});}}
const FormFieldSpec* FormBridge::spec(std::string_view id)const noexcept{auto i=std::find_if(fields_.begin(),fields_.end(),[&](const auto&x){return x.id==id;});return i==fields_.end()?nullptr:&*i;}
app::Result<void,FormError> FormBridge::set(std::string_view id,std::string v){if(pending_)return app::Result<void,FormError>::failure({FormErrorCode::Pending,"form.error.pending",{}});auto i=std::find_if(values_.begin(),values_.end(),[&](const auto&x){return x.id==id;});if(i==values_.end()||v.size()>4096)return app::Result<void,FormError>::failure({FormErrorCode::InvalidField,"form.error.invalid_field",std::string(id)});i->value=std::move(v);dirty_=true;errors_.erase(std::remove_if(errors_.begin(),errors_.end(),[&](const auto&e){return e.field==id;}),errors_.end());return app::Result<void,FormError>::success();}
std::optional<std::int64_t> FormBridge::integer(std::string_view s)noexcept{std::int64_t n{};auto x=std::from_chars(s.data(),s.data()+s.size(),n);return !s.empty()&&x.ec==std::errc{}&&x.ptr==s.data()+s.size()?std::optional{n}:std::nullopt;}
std::optional<std::int64_t> FormBridge::money(std::string_view s)noexcept{bool neg=!s.empty()&&s.front()=='-';if(neg)s.remove_prefix(1);auto dot=s.find('.');auto a=dot==s.npos?s:s.substr(0,dot),b=dot==s.npos?std::string_view{}:s.substr(dot+1);if(a.empty()||b.size()>2||!std::all_of(a.begin(),a.end(),::isdigit)||!std::all_of(b.begin(),b.end(),::isdigit))return{};auto major=integer(a);if(!major||*major>std::numeric_limits<std::int64_t>::max()/100)return{};std::int64_t n=*major*100;if(!b.empty())n+=(b[0]-'0')*10;if(b.size()==2)n+=b[1]-'0';return neg?-n:n;}
bool FormBridge::date(std::string_view s)noexcept{return s.size()==10&&s[4]=='-'&&s[7]=='-'&&std::all_of(s.begin(),s.end(),[i=std::size_t{0}](char c)mutable{return i++==4||i-1==7?c=='-':c>='0'&&c<='9';});}
app::Result<FormRequest,FormError> FormBridge::begin_submit(){if(pending_)return app::Result<FormRequest,FormError>::failure({FormErrorCode::Pending,"form.error.pending",{}});errors_.clear();std::vector<FormValue> out;for(std::size_t i=0;i<fields_.size();++i){auto&f=fields_[i];auto&v=values_[i].value;std::optional<std::int64_t> n;if(f.required&&v.empty())errors_.push_back({f.id,"form.error.required"});else if(f.kind==FormFieldKind::Integer&&!(n=integer(v)))errors_.push_back({f.id,"form.error.integer"});else if(f.kind==FormFieldKind::MoneyMinor&&!(n=money(v)))errors_.push_back({f.id,"form.error.money"});else if(f.kind==FormFieldKind::Date&&!date(v))errors_.push_back({f.id,"form.error.date"});else if(n&&f.has_range&&(*n<f.minimum||*n>f.maximum))errors_.push_back({f.id,"form.error.range"});else out.push_back({f.id,n?std::to_string(*n):v});}if(!errors_.empty())return app::Result<FormRequest,FormError>::failure({FormErrorCode::Validation,"form.error.validation",{}});pending_=true;return app::Result<FormRequest,FormError>::success({++generation_,context_,std::move(out)});}
app::Result<void,FormError> FormBridge::complete(std::uint64_t g,app::Result<std::string,app::DomainError> x){if(g!=generation_)return app::Result<void,FormError>::failure({FormErrorCode::Stale,"form.error.stale",{}});if(!pending_)return app::Result<void,FormError>::failure({FormErrorCode::NoPending,"form.error.no_pending",{}});pending_=false;if(x){saved_id_=x.value();dirty_=false;form_error_.reset();}else{auto p=present_domain_error(x.error());if(p.field&&spec(*p.field))errors_={{*p.field,p.message_key}};else form_error_=p;}return app::Result<void,FormError>::success();}
void FormBridge::cancel()noexcept{++generation_;pending_=false;errors_.clear();form_error_.reset();}
}
