cmake_minimum_required(VERSION 3.26)
foreach(required EXECUTABLE STAGE_DIR SOURCE_DIR WITH_QT)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing required staging argument: ${required}")
    endif()
endforeach()
if(NOT EXISTS "${EXECUTABLE}")
    message(FATAL_ERROR "Workstation executable does not exist: ${EXECUTABLE}")
endif()
file(REMOVE_RECURSE "${STAGE_DIR}")
file(MAKE_DIRECTORY "${STAGE_DIR}")
file(COPY "${EXECUTABLE}" DESTINATION "${STAGE_DIR}")
if(WITH_QT)
    if(NOT WINDEPLOYQT OR NOT EXISTS "${WINDEPLOYQT}")
        message(FATAL_ERROR "Qt build requested but windeployqt was not found")
    endif()
    execute_process(COMMAND "${WINDEPLOYQT}" --release --no-translations --no-system-d3d-compiler --no-opengl-sw "${STAGE_DIR}/squiflow_workstation.exe" RESULT_VARIABLE deploy_result OUTPUT_VARIABLE deploy_out ERROR_VARIABLE deploy_err)
    if(NOT deploy_result EQUAL 0)
        message(FATAL_ERROR "windeployqt failed (${deploy_result})\n${deploy_out}\n${deploy_err}")
    endif()
endif()
if(DEFINED WITH_UI_FLUENT AND WITH_UI_FLUENT)
    file(MAKE_DIRECTORY "${STAGE_DIR}/qml")
    file(COPY "${SOURCE_DIR}/external/ui-fluent/fluentcontrols"
         DESTINATION "${STAGE_DIR}/qml")
endif()
file(COPY "${SOURCE_DIR}/packaging/licenses" DESTINATION "${STAGE_DIR}")
