#include "platform/background_executor.hpp"
#include <exception>
#include <stdexcept>
#include <utility>
namespace squiflow::platform {
BackgroundExecutor::BackgroundExecutor(std::size_t capacity):capacity_(capacity){if(capacity_==0U)throw std::invalid_argument("background queue capacity is zero");sync_worker_=std::jthread([this](std::stop_token t){worker(BackgroundLane::Synchronization,t);});shared_worker_=std::jthread([this](std::stop_token t){worker(BackgroundLane::Shared,t);});}
BackgroundExecutor::~BackgroundExecutor(){(void)shutdown(BackgroundClock::duration::max());}
std::deque<BackgroundExecutor::Work>& BackgroundExecutor::queue(BackgroundLane l) noexcept{return l==BackgroundLane::Synchronization?sync_:shared_;}
SubmissionResult BackgroundExecutor::submit(BackgroundLane lane,std::string id,BackgroundTask task,BackgroundCompletion completion){if(!task||!completion)throw std::invalid_argument("background work callback is empty");{std::lock_guard lock(mutex_);if(stopping_)return SubmissionResult::Stopping;if(sync_.size()+shared_.size()>=capacity_)return SubmissionResult::QueueFull;queue(lane).push_back(Work{std::move(id),std::move(task),std::move(completion)});}cv_.notify_all();return SubmissionResult::Accepted;}
void BackgroundExecutor::worker(BackgroundLane lane,std::stop_token token) noexcept{std::stop_callback wake(token,[this]{cv_.notify_all();});for(;;){Work work;{std::unique_lock lock(mutex_);cv_.wait(lock,[&]{return token.stop_requested()||!queue(lane).empty();});if(token.stop_requested()&&queue(lane).empty())break;if(queue(lane).empty())continue;work=std::move(queue(lane).front());queue(lane).pop_front();++active_;}BackgroundOutcome outcome=BackgroundOutcome::Succeeded;std::string error;try{work.task(token);if(token.stop_requested())outcome=BackgroundOutcome::Cancelled;}catch(const std::exception& e){outcome=BackgroundOutcome::Failed;error=e.what();}catch(...){outcome=BackgroundOutcome::Failed;error="unknown background exception";}try{work.completion(outcome,std::move(error));}catch(...){ }{std::lock_guard lock(mutex_);--active_;exited_cv_.notify_all();}}{std::lock_guard lock(mutex_);++exited_;exited_cv_.notify_all();}}
ShutdownResult BackgroundExecutor::shutdown(BackgroundClock::duration timeout){std::deque<Work> cancelled;{std::lock_guard lock(mutex_);if(stopping_&&exited_==2U)return ShutdownResult::AlreadyStopped;stopping_=true;cancelled.insert(cancelled.end(),std::make_move_iterator(sync_.begin()),std::make_move_iterator(sync_.end()));cancelled.insert(cancelled.end(),std::make_move_iterator(shared_.begin()),std::make_move_iterator(shared_.end()));sync_.clear();shared_.clear();}sync_worker_.request_stop();shared_worker_.request_stop();cv_.notify_all();for(auto& work:cancelled){try{work.completion(BackgroundOutcome::Cancelled,"shutdown cancelled queued work");}catch(...){ }}bool clean=false;{std::unique_lock lock(mutex_);if(timeout==BackgroundClock::duration::max()){exited_cv_.wait(lock,[this]{return exited_==2U;});clean=true;}else clean=exited_cv_.wait_for(lock,timeout,[this]{return exited_==2U;});}if(clean){if(sync_worker_.joinable())sync_worker_.join();if(shared_worker_.joinable())shared_worker_.join();return ShutdownResult::Clean;}return ShutdownResult::DeadlineExceeded;}
std::size_t BackgroundExecutor::queued() const{std::lock_guard lock(mutex_);return sync_.size()+shared_.size();}bool BackgroundExecutor::stopping() const{std::lock_guard lock(mutex_);return stopping_;}
}
