#include "platform/background_supervisor.hpp"
#include <algorithm>
#include <limits>
#include <stdexcept>
#include <utility>
namespace squiflow::platform {
namespace {std::string bounded_error(std::string value){if(value.size()>kMaxBackgroundError)value.resize(kMaxBackgroundError);return value;}}
BackgroundSupervisor::BackgroundSupervisor(std::size_t capacity):executor_(capacity){snapshot_.store(std::make_shared<const std::vector<BackgroundServiceStatus>>(),std::memory_order_release);}
BackgroundSupervisor::~BackgroundSupervisor(){(void)shutdown(BackgroundClock::duration::max());}
void BackgroundSupervisor::register_service(BackgroundServiceDefinition d){validate_background_service(d);std::lock_guard lock(mutex_);if(sealed_)throw std::logic_error("background registry is sealed");if(entries_.size()>=kMaxBackgroundServices)throw std::length_error("too many background services");if(entries_.contains(d.id))throw std::invalid_argument("duplicate background service id");BackgroundServiceStatus status;status.id=d.id;const std::string key=d.id;entries_.emplace(key,Entry{std::move(d),std::move(status)});publish_locked();}
void BackgroundSupervisor::seal(){std::lock_guard lock(mutex_);sealed_=true;}
bool BackgroundSupervisor::gated(const Entry& e) const noexcept{return(e.definition.network_required&&!network_authorized_)||(e.definition.idle_required&&!idle_);}
SubmissionResult BackgroundSupervisor::trigger(std::string_view id,BackgroundTrigger reason){std::unique_lock lock(mutex_);if(stopping_)return SubmissionResult::Stopping;auto it=entries_.find(std::string(id));if(it==entries_.end())return SubmissionResult::UnknownService;return trigger_locked(it->second,reason,lock);}
SubmissionResult BackgroundSupervisor::trigger_locked(Entry& e,BackgroundTrigger reason,std::unique_lock<std::mutex>& lock){if(e.status.state==BackgroundState::Disabled)return SubmissionResult::Disabled;const auto bit=trigger_bit(reason);if(e.status.state==BackgroundState::Pending||e.status.state==BackgroundState::Running){e.rerun=true;e.rerun_triggers|=bit;e.status.pending_triggers|=bit;publish_locked();return SubmissionResult::Coalesced;}e.status.pending_triggers|=bit;if(gated(e)){e.status.state=BackgroundState::Pending;publish_locked();return SubmissionResult::Gated;}return dispatch_locked(e,lock);}
SubmissionResult BackgroundSupervisor::dispatch_locked(Entry& e,std::unique_lock<std::mutex>& lock){e.status.state=BackgroundState::Pending;const std::string id=e.definition.id;const auto lane=e.definition.lane;auto task=e.definition.task;publish_locked();lock.unlock();auto result=executor_.submit(lane,id,[this,id,task=std::move(task)](std::stop_token token){auto now=BackgroundClock::now();{std::lock_guard guard(mutex_);auto it=entries_.find(id);if(it==entries_.end())return;it->second.status.state=BackgroundState::Running;it->second.status.last_started=now;it->second.status.pending_triggers=0;++it->second.status.run_count;publish_locked();}task(token);},[this,id](BackgroundOutcome o,std::string error){completed(id,o,std::move(error));});lock.lock();if(result!=SubmissionResult::Accepted){e.status.state=BackgroundState::Idle;publish_locked();}return result;}
void BackgroundSupervisor::completed(const std::string& id,BackgroundOutcome outcome,std::string error){std::unique_lock lock(mutex_);auto it=entries_.find(id);if(it==entries_.end())return;auto& e=it->second;e.status.last_finished=BackgroundClock::now();e.status.last_outcome=outcome;e.status.last_error=bounded_error(std::move(error));if(outcome==BackgroundOutcome::Failed){if(e.status.consecutive_failures<std::numeric_limits<std::uint32_t>::max())++e.status.consecutive_failures;if(e.status.consecutive_failures>=e.definition.failure_limit){e.status.state=BackgroundState::Disabled;e.status.last_outcome=BackgroundOutcome::Disabled;e.rerun=false;e.rerun_triggers=0;publish_locked();return;}}else if(outcome==BackgroundOutcome::Succeeded)e.status.consecutive_failures=0;if(stopping_){e.status.state=BackgroundState::Stopping;e.rerun=false;publish_locked();return;}if(e.rerun){e.rerun=false;e.status.pending_triggers=e.rerun_triggers;e.rerun_triggers=0;if(gated(e)){e.status.state=BackgroundState::Pending;publish_locked();return;}(void)dispatch_locked(e,lock);return;}e.status.state=BackgroundState::Idle;publish_locked();}
void BackgroundSupervisor::coarse_tick(BackgroundClock::time_point now){std::vector<std::string> due;{std::lock_guard lock(mutex_);for(auto& [id,e]:entries_){if(!e.definition.interval)continue;if(!e.status.next_eligible)e.status.next_eligible=now+*e.definition.interval;else if(now>=*e.status.next_eligible){due.push_back(id);e.status.next_eligible=now+*e.definition.interval;}}publish_locked();}for(const auto& id:due)(void)trigger(id,BackgroundTrigger::CoarseTick);}
void BackgroundSupervisor::calendar_day(std::chrono::year_month_day day){if(!day.ok())throw std::invalid_argument("invalid calendar day");const auto current=std::chrono::sys_days(day);bool changed=false;{std::lock_guard lock(mutex_);changed=last_calendar_day_.has_value()&&current!=*last_calendar_day_;last_calendar_day_=current;}if(changed){std::vector<std::string> ids;{std::lock_guard lock(mutex_);for(const auto& [id,e]:entries_)if((e.status.pending_triggers&trigger_bit(BackgroundTrigger::DayRollover))!=0U||e.definition.idle_required)ids.push_back(id);}for(const auto& id:ids)(void)trigger(id,BackgroundTrigger::DayRollover);}}
void BackgroundSupervisor::set_network_authorized(bool v){std::unique_lock lock(mutex_);network_authorized_=v;if(!v)return;for(auto& [id,e]:entries_){(void)id;if(e.status.state==BackgroundState::Pending&&!gated(e)){e.status.pending_triggers|=trigger_bit(BackgroundTrigger::NetworkAvailable);(void)dispatch_locked(e,lock);}}}
void BackgroundSupervisor::set_idle(bool v){std::unique_lock lock(mutex_);idle_=v;if(!v)return;for(auto& [id,e]:entries_){(void)id;if(e.status.state==BackgroundState::Pending&&!gated(e)){e.status.pending_triggers|=trigger_bit(BackgroundTrigger::Idle);(void)dispatch_locked(e,lock);}}}
void BackgroundSupervisor::publish_locked(){auto values=std::make_shared<std::vector<BackgroundServiceStatus>>();values->reserve(entries_.size());for(const auto& [id,e]:entries_){(void)id;values->push_back(e.status);}std::sort(values->begin(),values->end(),[](const auto& a,const auto& b){return a.id<b.id;});snapshot_.store(std::const_pointer_cast<const std::vector<BackgroundServiceStatus>>(values),std::memory_order_release);}
std::vector<BackgroundServiceStatus> BackgroundSupervisor::statuses() const{return *snapshot_.load(std::memory_order_acquire);}std::optional<BackgroundServiceStatus> BackgroundSupervisor::status(std::string_view id) const{auto values=snapshot_.load(std::memory_order_acquire);auto it=std::find_if(values->begin(),values->end(),[&](const auto& v){return v.id==id;});if(it==values->end())return std::nullopt;return *it;}
ShutdownResult BackgroundSupervisor::shutdown(BackgroundClock::duration timeout){{std::lock_guard lock(mutex_);if(stopping_)return executor_.stopping()?ShutdownResult::AlreadyStopped:ShutdownResult::Clean;stopping_=true;for(auto& [id,e]:entries_){(void)id;e.status.state=BackgroundState::Stopping;e.rerun=false;}publish_locked();}return executor_.shutdown(timeout);}
bool BackgroundSupervisor::sealed() const{std::lock_guard lock(mutex_);return sealed_;}
}
