#include "platform/secrets.hpp"
#include "platform/secret_envelope.hpp"
#include "platform/secret_identity.hpp"
#include <windows.h>
#include <dpapi.h>
#include <filesystem>
#include <fstream>
#include <vector>
#include <memory>
#include <span>
#include <cstddef>
#include <string_view>
namespace squiflow::platform { namespace {
std::wstring wide(const std::string& s){return {s.begin(),s.end()};}
class DpapiStore final:public SecretStore{public:explicit DpapiStore(std::string root):root_(std::move(root)){}
SecretWriteResult store(std::string_view key,std::span<const std::byte> value)override{if(!is_valid_secret_key(key))return {false,SecretFault::InvalidKey,"Invalid secret key."};if(value.empty())return {false,SecretFault::EmptyValue,"Secret value is empty."};if(value.size()>kMaxSecretValueLength)return {false,SecretFault::ValueTooLarge,"Secret value is too large."};DATA_BLOB in{static_cast<DWORD>(value.size()),reinterpret_cast<BYTE*>(const_cast<std::byte*>(value.data()))},out{};if(!CryptProtectData(&in,L"SquiFlow workstation credential",nullptr,nullptr,nullptr,CRYPTPROTECT_UI_FORBIDDEN,&out))return {false,SecretFault::ProtectFailed,"Windows could not protect the credential."};std::vector<std::byte> protected_bytes(reinterpret_cast<std::byte*>(out.pbData),reinterpret_cast<std::byte*>(out.pbData)+out.cbData);SecureZeroMemory(out.pbData,out.cbData);LocalFree(out.pbData);const auto envelope=encode_secret_envelope(protected_bytes);const std::string destination=root_+"/"+secret_file_name(key);const std::string temporary=destination+".tmp";HANDLE file=CreateFileW(wide(temporary).c_str(),GENERIC_WRITE,0,nullptr,CREATE_ALWAYS,FILE_ATTRIBUTE_TEMPORARY|FILE_FLAG_OPEN_REPARSE_POINT,nullptr);if(file==INVALID_HANDLE_VALUE)return {false,SecretFault::WriteFailed,"Cannot create protected credential file."};DWORD written=0;const bool ok=WriteFile(file,envelope.data(),static_cast<DWORD>(envelope.size()),&written,nullptr)!=0&&written==envelope.size()&&FlushFileBuffers(file)!=0;CloseHandle(file);if(!ok){DeleteFileW(wide(temporary).c_str());return {false,SecretFault::WriteFailed,"Cannot write protected credential file."};}if(!MoveFileExW(wide(temporary).c_str(),wide(destination).c_str(),MOVEFILE_REPLACE_EXISTING|MOVEFILE_WRITE_THROUGH)){DeleteFileW(wide(temporary).c_str());return {false,SecretFault::ReplaceFailed,"Cannot replace protected credential file."};}return {true,SecretFault::None,{}};}
SecretReadResult load(std::string_view key)override{if(!is_valid_secret_key(key))return {false,SecretFault::InvalidKey,{},"Invalid secret key."};std::ifstream input(root_+"/"+secret_file_name(key),std::ios::binary);if(!input)return {false,SecretFault::NotFound,{},"Secret not found."};std::vector<std::byte> file;for(char ch;input.get(ch);)file.push_back(static_cast<std::byte>(ch));if(file.size()>kMaxProtectedSecretLength+kSecretEnvelopeHeaderSize)return {false,SecretFault::CorruptEnvelope,{},"Protected credential is invalid."};const auto decoded=decode_secret_envelope(file);if(!decoded.ok)return {false,decoded.fault,{},"Protected credential is invalid."};DATA_BLOB in{static_cast<DWORD>(decoded.protected_value.size()),reinterpret_cast<BYTE*>(const_cast<std::byte*>(decoded.protected_value.data()))},out{};LPWSTR description=nullptr;if(!CryptUnprotectData(&in,&description,nullptr,nullptr,nullptr,CRYPTPROTECT_UI_FORBIDDEN,&out))return {false,SecretFault::UnprotectFailed,{},"Windows could not unprotect the credential."};SecretBuffer result({reinterpret_cast<std::byte*>(out.pbData),out.cbData});SecureZeroMemory(out.pbData,out.cbData);LocalFree(out.pbData);if(description)LocalFree(description);return {true,SecretFault::None,std::move(result),{}};}
SecretDeleteResult erase(std::string_view key)override{if(!is_valid_secret_key(key))return {false,false,SecretFault::InvalidKey,"Invalid secret key."};const auto path=wide(root_+"/"+secret_file_name(key));if(DeleteFileW(path.c_str()))return {true,true,SecretFault::None,{}};if(GetLastError()==ERROR_FILE_NOT_FOUND)return {true,false,SecretFault::None,{}};return {false,false,SecretFault::DeleteFailed,"Cannot delete protected credential."};}
private:std::string root_;};}
std::unique_ptr<SecretStore> make_secret_store(const std::string& directory){return std::make_unique<DpapiStore>(directory);} }
