#include "platform/single_instance.hpp"
#include "platform/single_instance_name.hpp"
#include <windows.h>
#include <string>
namespace squiflow::platform {
namespace {
std::wstring widen(const std::string& s){return {s.begin(),s.end()};}
class WindowsLock final:public SingleInstanceLock{public:~WindowsLock()override{release();}InstanceAcquireResult acquire(const std::string& id,const std::string& dir)override{if(state_!=InstanceState::Idle)return fail(InstanceFault::LockWaitFailed,"Lock object already used.");const auto n=make_single_instance_names(id,dir);if(!n.ok)return fail(InstanceFault::InvalidDataDirectory,n.error.c_str());event_=CreateEventW(nullptr,FALSE,FALSE,widen(n.activation_name).c_str());if(event_==nullptr)return fail(InstanceFault::ActivationCreateFailed,"Cannot create activation event.");mutex_=CreateMutexW(nullptr,FALSE,widen(n.mutex_name).c_str());if(mutex_==nullptr){release();return fail(InstanceFault::LockCreateFailed,"Cannot create named mutex.");}const DWORD wait=WaitForSingleObject(mutex_,0);if(wait==WAIT_OBJECT_0||wait==WAIT_ABANDONED){owned_=true;state_=InstanceState::Primary;return {state_,InstanceFault::None,"Primary instance acquired.",wait==WAIT_ABANDONED};}if(wait==WAIT_TIMEOUT){if(SetEvent(event_)==0){release();return fail(InstanceFault::ActivationSignalFailed,"Cannot signal primary instance.");}state_=InstanceState::Secondary;return {state_,InstanceFault::None,"Existing instance notified.",false};}release();return fail(InstanceFault::LockWaitFailed,"Cannot wait for named mutex.");}bool take_activation_request()noexcept override{return state_==InstanceState::Primary&&WaitForSingleObject(event_,0)==WAIT_OBJECT_0;}InstanceState state()const noexcept override{return state_;}void release()noexcept override{if(owned_&&mutex_!=nullptr)ReleaseMutex(mutex_);owned_=false;if(mutex_)CloseHandle(mutex_);if(event_)CloseHandle(event_);mutex_=nullptr;event_=nullptr;state_=InstanceState::Idle;}private:InstanceAcquireResult fail(InstanceFault f,const char* m){state_=InstanceState::Failed;return {state_,f,m,false};}HANDLE mutex_{nullptr};HANDLE event_{nullptr};bool owned_{false};InstanceState state_{InstanceState::Idle};};}
std::unique_ptr<SingleInstanceLock> make_single_instance_lock(){return std::make_unique<WindowsLock>();}
}  // namespace squiflow::platform
